message("Building test utilities.")

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_DEBUG}")
else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_MINSIZEREL}")
endif()

# message("CMAKE_C_FLAGS = ${CMAKE_C_FLAGS}")

# Build test executables
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_subdirectory("unit")
endif()
add_subdirectory("stress_api_lock")
add_subdirectory("stress_rc_mem")
add_subdirectory("stress_test")
add_subdirectory("test_array_notation")
add_subdirectory("test_auto_read")
add_subdirectory("test_auto_sync")
add_subdirectory("test_auto_sync_modbus")
add_subdirectory("test_callback")
add_subdirectory("test_callback_ex")
add_subdirectory("test_callback_ex_logix")
add_subdirectory("test_callback_ex_modbus")
add_subdirectory("test_connection_group")
add_subdirectory("test_connection_stress")
add_subdirectory("test_device_tag")
add_subdirectory("test_emulator_performance")
add_subdirectory("test_event")
add_subdirectory("test_fairness")
add_subdirectory("test_idle_disconnect")
add_subdirectory("test_indexed_tags")
add_subdirectory("test_modbus_multiple")
add_subdirectory("test_raw_cip")
add_subdirectory("test_reconnect")
add_subdirectory("test_reconnect_after_outage_async")
add_subdirectory("test_reconnect_after_outage_sync")
add_subdirectory("test_shutdown_cip")
add_subdirectory("test_shutdown_modbus")
add_subdirectory("test_shutdown_restart")
add_subdirectory("test_simultaneous_rw_ab_server")
add_subdirectory("test_special")
add_subdirectory("test_string")
add_subdirectory("test_tag_attributes")
add_subdirectory("test_tag_type_attribute")
add_subdirectory("thread_stress")
add_subdirectory("trigger_double_free")
add_subdirectory("perf_benchmark")


