trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: 'sudo apt update; sudo apt-get -y --force-yes install gcc-multilib g++-multilib'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DBUILD_32_BIT=1 ..'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '--build .'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/bin_dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/libplctag_ubuntu_x86_$(Build.BuildId).zip'
    replaceExistingArchive: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/lib/libplctag.h'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/libplctag_ubuntu_x86_$(Build.BuildId).zip'
    replaceExistingArchive: false

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/libplctag_ubuntu_x86_$(Build.BuildId).zip'
    artifactName: libplctag_ubuntu_x86_$(Build.BuildId)