#!/usr/bin/perl

use strict;


my %allocs = {};

my $line;

while($line = <>) {
	chomp($line);

	if($line =~ m/memory pointer (0x[0-9a-f]+)$/) {
		$allocs{"$1"} = "not freed";
	}

	if($line =~ m/for (0x[0-9a-f]+)\./) {
		$allocs{"$1"} = "freed";
	}
}


foreach my $alloc (sort keys(%allocs)) {
	if(%allocs{$alloc} eq "not freed") {
		print "$alloc is not freed.\n";
	}
}


