Document: libplctag
Title: Debian libplctag Manual
Author: <insert document author here>
Abstract: This manual describes what libplctag is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libplctag/libplctag.sgml.gz

Format: postscript
Files: /usr/share/doc/libplctag/libplctag.ps.gz

Format: text
Files: /usr/share/doc/libplctag/libplctag.text.gz

Format: HTML
Index: /usr/share/doc/libplctag/html/index.html
Files: /usr/share/doc/libplctag/html/*.html
