message("Building for Linux (Ubuntu/Debian) Arm v7 32-bit")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
set(CMAKE_C_FLAGS "-march=armv7-a")
set(CMAKE_CXX_FLAGS "-march=armv7-a")
set(CMAKE_EXE_LINKER_FLAGS "-latomic")
set(CMAKE_SHARED_LINKER_FLAGS "-latomic")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
