message("Building for Linux (Ubuntu/Debian) Arm v6")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_C_COMPILER arm-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabi-g++)
set(CMAKE_C_FLAGS "-march=armv6 -mfpu=vfp -mfloat-abi=softfp")
set(CMAKE_CXX_FLAGS "-march=armv6 -mfpu=vfp -mfloat-abi=softfp")
set(EXTRA_LINKER_LIBS "${EXTRA_LINKER_LIBS}" atomic)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)