
set(PLATFORM_WINDOWS True)

set(PLATFORM_SHIM_PATH "${CMAKE_SOURCE_DIR}/src/platform/windows" )

set (EXTRA_LINKER_LIBS "${EXTRA_LINKER_LIBS}" ws2_32 bcrypt)

set(EXTRA_COMPILER_DEFINITIONS ${EXTRA_COMPILER_DEFINITIONS} "/D _CRT_SECURE_NO_WARNINGS")
set(EXTRA_COMPILER_DEFINITIONS ${EXTRA_COMPILER_DEFINITIONS} "/D WIN32_LEAN_AND_MEAN")

if(CMAKE_GENERATOR_PLATFORM STREQUAL "x64")
    message(STATUS "Building for x64 architecture")
    set(EXTRA_COMPILER_DEFINITIONS ${EXTRA_COMPILER_DEFINITIONS} "/D _M_X64")
elseif(CMAKE_GENERATOR_PLATFORM STREQUAL "Win32")
    message(STATUS "Building for x86 architecture")
    set(EXTRA_COMPILER_DEFINITIONS ${EXTRA_COMPILER_DEFINITIONS} "/D _M_IX86")
elseif(CMAKE_GENERATOR_PLATFORM STREQUAL "ARM")
    message(STATUS "Building for ARM architecture")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D _M_ARM")
elseif(CMAKE_GENERATOR_PLATFORM STREQUAL "ARM64")
    message(STATUS "Building for ARM64 architecture")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /D _M_ARM64")
else()
    message(WARNING "Unknown architecture: ${CMAKE_GENERATOR_PLATFORM}")
endif()